### ISSUE TITLE
Regression in 2.15: parsing double value returns BigDecimal instead of Double

### ISSUE THREAD

**Issue by dlipin** [FasterXML/jackson-datatypes-misc#39]
I'm filing this issue as the result of conversation in pull request:
https://github.com/FasterXML/jackson-datatypes-misc/pull/32

Here is the test:
```package com.company.test;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsonorg.JsonOrgModule;
import org.json.JSONObject;
import org.junit.Assert;
import org.junit.Test;

public class JsonDoubleTest {

    @Test
    public void testDoubleParsing() throws Exception {
        ObjectMapper objectMapper = new ObjectMapper().registerModule(new JsonOrgModule());
        JSONObject jsonObject = objectMapper.readValue("{\"value\": 0.5 }", JSONObject.class);
        Assert.assertEquals("java.lang.Double", jsonObject.get("value").getClass().getCanonicalName());
    }
}
```

When I run it with Jackson 2.13.4 then it passes. When I run it with Jackson 2.15.0, it fails with error:
```
org.junit.ComparisonFailure: 
Expected :java.lang.Double
Actual   :java.math.BigDecimal
```

**Comment by cowtowncoder** [comment]
Ok so the question is: is the new behavior erroneous? Yes, it is a change and in hindsight unfortunate. But given there is new behavior for 2.15 I am not sure reverting change is the right thing to do.

Also see #38 for more discussion. 

One possible way forward would be to support `DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS`, but problem there is that it is disabled by default so using it to determine behavior would mean reverting behavior.
Yet another possibility would be module-specific Feature.

@pjfanning WDYT?

**Comment by pjfanning** [comment]
This is very easily worked around - see https://github.com/FasterXML/jackson-datatypes-misc/pull/32#issuecomment-1665267589

The old behaviour had a bug. It did not handle big numbers properly. Users who want doubles can still get doubles by using the API to ask for a Double.

**Comment by cowtowncoder** [comment]
Ok I think I'll close this then, after tests were added to document the new behavior.
