### ISSUE TITLE
Jackson JSR353 library is using wrong module name for javax json api

### ISSUE THREAD

**Issue by moquinr** [FasterXML/jackson-datatypes-misc#7]
In the jsr353 module, the javax json api module require statement is using the wrong module name, resulting in this error:

java.lang.module.FindException: Module javax.json.api not found, required by com.fasterxml.jackson.datatype.jsr353

The "correct" name (in quotes because there is no consistency in the jakarta projects on how they named the javax modules :( ) is java.json.

So it should be 

    requires java.json;

rather than

    requires javax.json.api;

**Comment by cowtowncoder** [comment]
@moquinr sounds reasonable -- I don't use module system in general, nor this module specifically, so I rely on others to find out these issues.

@GedMarc any comments? Is this yet another thing that has changed over time, or did I just guess wrong module name originally? But most importantly, do you agree with the change proposed?

**Comment by moquinr** [comment]
Your guess would have been correct if it was using the automated module name.  Honestly, I didn't think the jar would have a module descriptor in it, so I'm guessing you probably didn't either. :)

**Comment by cowtowncoder** [comment]
@moquinr no, and I think there may also have been complications about multiple competing api jars with possibly conflicting settings (often seems to happen with jcp/jsr jars). But not saying there necessarily was any solid reasoning involved :)

**Comment by cowtowncoder** [comment]
Looking at jar itself, yes, declared module name is "java.json" so making the change as suggested (confirmed by `javap` on `module-info.class`).

**Comment by GedMarc** [comment]
Naw i have no idea on this, i do see java.json though

![image](https://user-images.githubusercontent.com/5367513/104064565-d4e52300-5206-11eb-8c05-0090e682124a.png)

**Comment by moquinr** [comment]
Thanks guys!

**Comment by cowtowncoder** [comment]
Released in 2.12.1.
